### PR TITLE
✨ Onboard AUSD Aave v3 Avalanche

### PR DESCRIPTION
**Pull request by MartinGbz**
I've added a transfer of the seed amount from the Collector to the Executor, because an error has been done in the transfer of the seed funds.

### CODE REVIEW

**Comment by sakulstra** [comment]
The risk assessment by us is still pending on this one and probably needs a capo feed.
Will get back to you once i got news on the topic.

**Comment by MartinGbz** [comment]
@sakulstra Okay np, thanks for the info

Just have a question, I got a weird error on the `test_defaultProposalExecution` test.
[FAIL: revert: stdStorage find(StdStorage): Failed to write value.] => it seems to be an error with deal() from foundry

I didn't have this error before, and I still don't have this error in other AIP PRs.
I tried `forge install`, `forge update`, `forge build --force`, `forge clean`... etc, but still have the issue.

Any idea?

**Comment by sakulstra** [comment]
@MartinGbz didn't yet check but probably AUSD does some fancy things on _balances storage.
Foundry deal essentially checks if it's a uint and if not reverts.
We maintain a list of tokens here: https://github.com/bgd-labs/aave-helpers/blob/master/src/CommonTestBase.sol#L45 that cannot be dealt.

**Comment by MartinGbz** [comment]
@sakulstra Thanks for this, now it works like a charm. The lib is updated, test are passing, the PR is ready for a review.

**Comment by MartinGbz** [comment]
The oracle has been update for the new CAPO one: https://snowtrace.io/address/0x83f32c0882B12Ef16214c417efF11FD9e764bf34

**Review by sakulstra — APPROVED** [review]

**Review by TepNik — APPROVED** [review]

**Pull request merged**
